apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barramento
  template:
    metadata:
      labels:
        app: barramento
    spec:
      containers:
        - name: barramento
          image: barramento_eventos-barramento_eventos
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 256Mi
              cpu: 1
          ports:
            - containerPort: 3100

---
apiVersion: v1
kind: Service
metadata:
  name: barramento-service
spec:
  type: NodePort
  selector:
    app: barramento
  ports:
    - port: 3100
      targetPort: 3100
