apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: mss_login-mss_login
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 256Mi
              cpu: 1
          ports:
            - containerPort: 3100

---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 3100
      targetPort: 3100
