apiVersion: apps/v1
kind: Deployment
metadata:
  name: produto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produto
  template:
    metadata:
      labels:
        app: produto
    spec:
      containers:
        - name: produto
          image: mss_produto-mss_produto
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 256Mi
              cpu: 1
          ports:
            - containerPort: 3030

---
apiVersion: v1
kind: Service
metadata:
  name: produto-service
spec:
  type: NodePort
  selector:
    app: produto
  ports:
    - port: 3030
      targetPort: 3030
